# Generated by Django 4.1.5 on 2023-01-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='processed_image_url',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='raw_image_url',
            field=models.CharField(max_length=256),
        ),
    ]
