# Generated by Django 4.1.5 on 2023-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_receipt_processed_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private_key',
            field=models.CharField(default='DLYa4h9OKXrM37JQTPKzSC0OMpCA2Ym2', max_length=32),
        ),
    ]
