# Generated by Django 4.1.5 on 2023-01-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_userprofile_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='private_key',
        ),
    ]
